const options = [
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "javascript", label: "JavaScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "c++", label: "C++" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "swift", label: "Swift" },
  { value: "react", label: "React" },
  { value: "angular", label: "Angular" },
  { value: "vue.js", label: "Vue.js" },
  { value: "node.js", label: "Node.js" },
  { value: "sql", label: "SQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "git", label: "Git" },
  { value: "aws", label: "AWS" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "tensorflow", label: "TensorFlow" },
  { value: "machine learning", label: "Machine Learning" },
  { value: "artificial intelligence", label: "Artificial Intelligence" },
  { value: "data science", label: "Data Science" },
  { value: "ui/ux design", label: "UI/UX Design" },
  { value: "graphic design", label: "Graphic Design" },
  { value: "mobile app development", label: "Mobile App Development" },
  { value: "web development", label: "Web Development" },
  { value: "backend development", label: "Backend Development" },
  { value: "frontend development", label: "Frontend Development" },
  { value: "full stack development", label: "Full Stack Development" },
  { value: "responsive web design", label: "Responsive Web Design" },
  { value: "software engineering", label: "Software Engineering" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "network administration", label: "Network Administration" },
  { value: "devops", label: "DevOps" },
  { value: "agile methodology", label: "Agile Methodology" },
  { value: "scrum", label: "Scrum" },
  { value: "project management", label: "Project Management" },
  { value: "quality assurance", label: "Quality Assurance" },
  { value: "mobile app design", label: "Mobile App Design" },
  { value: "database management", label: "Database Management" },
  { value: "content writing", label: "Content Writing" },
  { value: "copywriting", label: "Copywriting" },
  { value: "digital marketing", label: "Digital Marketing" },
  { value: "seo", label: "SEO" },
  { value: "social media marketing", label: "Social Media Marketing" },
  { value: "product management", label: "Product Management" },
  { value: "salesforce", label: "Salesforce" },
  { value: "big data", label: "Big Data" },
  { value: "blockchain", label: "Blockchain" },
  { value: "rust", label: "Rust" },
  { value: "go", label: "Go" },
  { value: "typescript", label: "TypeScript" },
  { value: "angularjs", label: "AngularJS" },
  { value: "express.js", label: "Express.js" },
  { value: "ruby on rails", label: "Ruby on Rails" },
  { value: "asp.net", label: "ASP.NET" },
  { value: "c#", label: "C#" },
  { value: "perl", label: "Perl" },
  { value: "bash/shell scripting", label: "Bash/Shell Scripting" },
  { value: "sass", label: "Sass" },
  { value: "less", label: "LESS" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "material-ui", label: "Material-UI" },
  { value: "tailwind css", label: "Tailwind CSS" },
  { value: "graphql", label: "GraphQL" },
  { value: "restful apis", label: "RESTful APIs" },
  { value: "firebase", label: "Firebase" },
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "oracle", label: "Oracle" },
  { value: "sqlite", label: "SQLite" },
  { value: "nosql", label: "NoSQL" },
  { value: "redis", label: "Redis" },
  { value: "elasticsearch", label: "Elasticsearch" },
  { value: "linux", label: "Linux" },
  { value: "windows server", label: "Windows Server" },
  { value: "macos", label: "MacOS" },
  { value: "azure", label: "Azure" },
  { value: "google cloud platform", label: "Google Cloud Platform" },
  { value: "aws lambda", label: "AWS Lambda" },
  { value: "serverless architecture", label: "Serverless Architecture" },
  { value: "microservices", label: "Microservices" },
  { value: "kafka", label: "Kafka" },
  { value: "rabbitmq", label: "RabbitMQ" },
  { value: "nginx", label: "Nginx" },
  { value: "apache", label: "Apache" },
  { value: "junit", label: "JUnit" },
  { value: "selenium", label: "Selenium" },
  { value: "jenkins", label: "Jenkins" },
  { value: "ansible", label: "Ansible" },
  { value: "chef", label: "Chef" },
  { value: "terraform", label: "Terraform" },
  { value: "kotlin", label: "Kotlin" },
  { value: "objective-c", label: "Objective-C" },
  { value: "ionic framework", label: "Ionic Framework" },
  { value: "flutter", label: "Flutter" },
  { value: "adobe photoshop", label: "Adobe Photoshop" },
  { value: "adobe illustrator", label: "Adobe Illustrator" },
];

export default options;
